In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
import os
path=os.getcwd()+"\\Pro Kabbadi Hackathon"
files=[]
files=os.listdir(path) #Getting the results for the first six seasons

In [3]:
#Taking a look at the files
files

['AugustS7_fixtures.csv',
 'JulyS7_fixtures.csv',
 'OctoberS7_fixtures.csv',
 'player_stats.csv',
 'Season 1_fixtures.csv',
 'season 1_standings.csv',
 'Season 2_fixtures.csv',
 'season 2_standings.csv',
 'Season 3_fixtures.csv',
 'season 3_standings.csv',
 'Season 4_fixtures.csv',
 'season 4_standings.csv',
 'Season 5_fixtures.csv',
 'season 5_standings.csv',
 'Season 6_fixtures.csv',
 'season 6_standings.csv',
 'season 7_standings.csv',
 'SeptemberS7_fixtures.csv',
 'team_stats.csv']

In [4]:
#Selecting the files which have 'fixtures' in the name
lis=[]
for i in range(0,len(files)):
    if 'fixtures' in files[i]:
        lis.append(files[i])
lis

['AugustS7_fixtures.csv',
 'JulyS7_fixtures.csv',
 'OctoberS7_fixtures.csv',
 'Season 1_fixtures.csv',
 'Season 2_fixtures.csv',
 'Season 3_fixtures.csv',
 'Season 4_fixtures.csv',
 'Season 5_fixtures.csv',
 'Season 6_fixtures.csv',
 'SeptemberS7_fixtures.csv']

In [5]:
#Reading and Concatenating the files along the rows to form a df of all matches.
f1=pd.DataFrame()
for f in lis:
    s=pd.read_csv(path+"\\"+f)
    f1=pd.concat([f1,s])

In [6]:
#All the mathch fixtures
f1=f1.reset_index(drop=True)
f1.tail()

,match_date,time,match_status,Team1,Team2,scores,venue,team1_score,team2_score,Season
647,"Saturday, 28 September",20:30 (IST),Match 112 - Upcoming,Gujarat Fortunegiants,Tamil Thalaivas,-,"Tau Devilal Sports Complex, Panchkula",NaN,NaN,September
648,"Sunday, 29 September",19:30 (IST),Match 113 - Upcoming,Puneri Paltan,Dabang Delhi K.C.,-,"Tau Devilal Sports Complex, Panchkula",NaN,NaN,September
649,"Sunday, 29 September",20:30 (IST),Match 114 - Upcoming,Haryana Steelers,Gujarat Fortunegiants,-,"Tau Devilal Sports Complex, Panchkula",NaN,NaN,September
650,"Monday, 30 September",19:30 (IST),Match 115 - Upcoming,Bengal Warriors,Dabang Delhi K.C.,-,"Tau Devilal Sports Complex, Panchkula",NaN,NaN,September
651,"Monday, 30 September",20:30 (IST),Match 116 - Upcoming,Tamil Thalaivas,U Mumba,-,"Tau Devilal Sports Complex, Panchkula",NaN,NaN,September

In [8]:
f1['Season'][f1.Season.str.find('Season')<0]="Season 7"

C:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
f1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 10 columns):
match_date      652 non-null object
time            652 non-null object
match_status    652 non-null object
Team1           652 non-null object
Team2           652 non-null object
scores          652 non-null object
venue           652 non-null object
team1_score     620 non-null float64
team2_score     620 non-null float64
Season          652 non-null object
dtypes: float64(2), object(8)
memory usage: 51.0+ KB

In [11]:
f1['Winning Team']=np.where((f1['team1_score']>f1['team2_score']),1,0)
f1['Winning_Team_Name']=np.where((f1['team1_score']>f1['team2_score']),f1['Team1'],
                                 f1['Team2'])

Here 1 signifies that Team1 has won the match, otherwise team2 has one the match.

For the purposes of simplicity have not yet coded 'DRAW' as a prediction.

In [12]:
#Team name and their total wins
f1['Winning_Team_Name'].value_counts().head(12)

U Mumba                  84
Patna Pirates            76
Bengaluru Bulls          66
Bengal Warriors          63
Telugu Titans            59
Jaipur Pink Panthers     58
Puneri Paltan            56
Dabang Delhi K.C.        54
Gujarat Fortunegiants    44
Haryana Steelers         33
U.P. Yoddha              32
Tamil Thalaivas          22
Name: Winning_Team_Name, dtype: int64

In [13]:
#Team wins per season
f1.groupby(['Winning_Team_Name','Season'])['Winning Team'].count()

Winning_Team_Name       Season
Bengal Warriors         Season 1     5
                        Season 2     5
                        Season 3     9
                        Season 4     4
                        Season 5    14
                        Season 6    14
                        Season 7    12
Bengaluru Bulls         Season 1     9
                        Season 2    10
                        Season 3     2
                        Season 4     6
                        Season 5     9
                        Season 6    17
                        Season 7    13
Dabang Delhi K.C.       Season 1     6
                        Season 2     4
                        Season 3     1
                        Season 4     5
                        Season 5     6
                        Season 6    13
                        Season 7    19
Gujarat Fortunegiants   Season 5    16
                        Season 6    19
                        Season 7     9
Haryana Steelers        Season 5    14
                        Season 6     7
                        Season 7    12
Jaipur Pink Panthers    Season 1    12
                        Season 2     7
                        Season 3     6
                                    ..
Puneri Paltan           Season 3     9
                        Season 4     7
                        Season 5    16
                        Season 6     9
                        Season 7    10
Rank 5                  Season 7     1
Rank 6                  Season 7     1
Tamil Thalaivas         Season 5     8
                        Season 6     7
                        Season 7     7
Telugu Titans           Season 1     7
                        Season 2    10
                        Season 3     7
                        Season 4    10
                        Season 5     8
                        Season 6     9
                        Season 7     8
U Mumba                 Season 1    11
                        Season 2    14
                        Season 3    13
                        Season 4     7
                        Season 5    10
                        Season 6    17
                        Season 7    12
U.P. Yoddha             Season 5    11
                        Season 6    10
                        Season 7    11
Winner of Semi-Final 2  Season 7     1
Winner ofEliminator 1   Season 7     1
Winner ofEliminator 2   Season 7     1
Name: Winning Team, Length: 73, dtype: int64

In [14]:
#Saving the home venues of all the teams - 
home={'Netaji Subhash Chandra Bose Indoor Stadium, Kolkata':'Bengal Warriors',
 'Sree Kanteerava Stadium, Bengaluru':'Bengaluru Bulls',
 'Thyagaraj Sports Complex, Delhi':'Dabang Delhi K.C.',
 'EKA Arena by TransStadia, Ahmedabad':'Gujarat Fortunegiants',
 'Tau Devilal Sports Complex, Panchkula':'Haryana Steelers',
 'Sawai Mansingh Stadium, Jaipur':'Jaipur Pink Panthers',
 'Patliputra Sports Complex, Patna':'Patna Pirates',
 'Shree Shiv Chhatrapati Sports Complex, Pune':'Puneri Paltan',
 'Jawaharlal Nehru Indoor Stadium, Chennai':'Tamil Thalaivas',
 'Gachibowli Indoor Stadium, Hyderabad':'Telugu Titans',
 'Dome, NSCI, SVP Stadium, Mumbai':'U Mumba',
 'Shaheed Vijay Singh Pathik Sports Complex, Greater Noida':'U.P. Yoddha'
}  

c=f1['venue'].replace(home)

f1['Team1_venue']=np.where((f1['Team1']==c),"Home","Away")

In [15]:
#The home ground team does not seem to particularly have an advantage 
f1.groupby(['Team1','Team1_venue'])['Winning Team'].sum()[0:16]

Team1                  Team1_venue
Bengal Warriors        Away           17
                       Home           16
Bengaluru Bulls        Away           19
                       Home            9
Dabang Delhi K.C.      Away           14
                       Home           12
Gujarat Fortunegiants  Away           19
                       Home            0
Haryana Steelers       Away            7
                       Home            0
Jaipur Pink Panthers   Away           17
                       Home            8
Patna Pirates          Away           23
                       Home           10
Puneri Paltan          Away           15
                       Home           11
Name: Winning Team, dtype: int32

In [16]:
#Doing this in order to get the match queue in order
f1['match_number']=f1['match_status'].str.split(" ",expand=True)[1]
#Replacing the semifinals and finals with a very high number (req for later)
f1['match_number']=f1['match_number'].replace({'-':1000,'Place':999})
f1['match_number']=f1['match_number'].astype('int64')

In [17]:
f1=f1.sort_values(['Season','match_number']).reset_index(drop=True)

In [19]:
#We have a sorted df of matches by season
f1.head()

,match_date,time,match_status,Team1,Team2,scores,venue,team1_score,team2_score,Season,Winning Team,Winning_Team_Name,Team1_venue,match_number
0,"Saturday, 26 July",20:00 (IST),Match 1 - Completed,U Mumba,Jaipur Pink Panthers,45- 31,"DOME@NSCI SVP Stadium, Mumbai",45.0,31.0,Season 1,1,U Mumba,Away,1
1,"Friday, 29 August",05:30 (IST),Semi-Final 1 - Completed,Jaipur Pink Panthers,Patna Pirates,38- 18,"DOME@NSCI SVP Stadium, Mumbai",38.0,18.0,Season 1,1,Jaipur Pink Panthers,Away,1
2,"Saturday, 26 July",21:00 (IST),Match 2 - Completed,Dabang Delhi K.C.,Bengaluru Bulls,28- 47,"DOME@NSCI SVP Stadium, Mumbai",28.0,47.0,Season 1,0,Bengaluru Bulls,Away,2
3,"Friday, 29 August",05:30 (IST),Semi-Final 2 - Completed,U Mumba,Bengaluru Bulls,27- 23,"DOME@NSCI SVP Stadium, Mumbai",27.0,23.0,Season 1,1,U Mumba,Away,2
4,"Sunday, 27 July",20:00 (IST),Match 3 - Completed,Bengaluru Bulls,Puneri Paltan,40- 37,"DOME@NSCI SVP Stadium, Mumbai",40.0,37.0,Season 1,1,Bengaluru Bulls,Away,3

In [20]:
#Saving a list of team names
team_names=list(f1['Team1'].value_counts().index)[0:12]

In [21]:
f1.head()

,match_date,time,match_status,Team1,Team2,scores,venue,team1_score,team2_score,Season,Winning Team,Winning_Team_Name,Team1_venue,match_number
0,"Saturday, 26 July",20:00 (IST),Match 1 - Completed,U Mumba,Jaipur Pink Panthers,45- 31,"DOME@NSCI SVP Stadium, Mumbai",45.0,31.0,Season 1,1,U Mumba,Away,1
1,"Friday, 29 August",05:30 (IST),Semi-Final 1 - Completed,Jaipur Pink Panthers,Patna Pirates,38- 18,"DOME@NSCI SVP Stadium, Mumbai",38.0,18.0,Season 1,1,Jaipur Pink Panthers,Away,1
2,"Saturday, 26 July",21:00 (IST),Match 2 - Completed,Dabang Delhi K.C.,Bengaluru Bulls,28- 47,"DOME@NSCI SVP Stadium, Mumbai",28.0,47.0,Season 1,0,Bengaluru Bulls,Away,2
3,"Friday, 29 August",05:30 (IST),Semi-Final 2 - Completed,U Mumba,Bengaluru Bulls,27- 23,"DOME@NSCI SVP Stadium, Mumbai",27.0,23.0,Season 1,1,U Mumba,Away,2
4,"Sunday, 27 July",20:00 (IST),Match 3 - Completed,Bengaluru Bulls,Puneri Paltan,40- 37,"DOME@NSCI SVP Stadium, Mumbai",40.0,37.0,Season 1,1,Bengaluru Bulls,Away,3

In [22]:
#Finding the completed matches
matches_completed=f1[f1['match_status'].str.split('-',expand=True)[1].str.strip()=="Completed"]
matches_upcoming=f1[f1['match_status'].str.split('-',expand=True)[1].str.strip()=="Upcoming"]

In [23]:
win_count=matches_completed[['Team1','Team2','Season','Winning_Team_Name']]
win_count['Opposing_Team']=np.where(win_count['Team1']==win_count['Winning_Team_Name'],win_count['Team2'],win_count['Team1'])

for i in team_names:
    win_count[i]=0
    win_count[i]=np.where(win_count['Winning_Team_Name']==i,1,0)
win_count.head()

C:\anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Team1,Team2,Season,Winning_Team_Name,Opposing_Team,U Mumba,Patna Pirates,Bengal Warriors,Jaipur Pink Panthers,Puneri Paltan,Dabang Delhi K.C.,Telugu Titans,Bengaluru Bulls,Gujarat Fortunegiants,U.P. Yoddha,Haryana Steelers,Tamil Thalaivas
0,U Mumba,Jaipur Pink Panthers,Season 1,U Mumba,Jaipur Pink Panthers,1,0,0,0,0,0,0,0,0,0,0,0
2,Dabang Delhi K.C.,Bengaluru Bulls,Season 1,Bengaluru Bulls,Dabang Delhi K.C.,0,0,0,0,0,0,0,1,0,0,0,0
4,Bengaluru Bulls,Puneri Paltan,Season 1,Bengaluru Bulls,Puneri Paltan,0,0,0,0,0,0,0,1,0,0,0,0
5,U Mumba,Bengal Warriors,Season 1,U Mumba,Bengal Warriors,1,0,0,0,0,0,0,0,0,0,0,0
6,Puneri Paltan,Dabang Delhi K.C.,Season 1,Dabang Delhi K.C.,Puneri Paltan,0,0,0,0,0,1,0,0,0,0,0,0

# Perfect (now use this)
For head to head each season

In [24]:
win_count.groupby(['Opposing_Team','Season']).sum().reset_index()

,Opposing_Team,Season,U Mumba,Patna Pirates,Bengal Warriors,Jaipur Pink Panthers,Puneri Paltan,Dabang Delhi K.C.,Telugu Titans,Bengaluru Bulls,Gujarat Fortunegiants,U.P. Yoddha,Haryana Steelers,Tamil Thalaivas
0,Bengal Warriors,Season 1,2,1,0,2,1,1,0,2,0,0,0,0
1,Bengal Warriors,Season 2,2,1,0,0,1,1,2,2,0,0,0,0
2,Bengal Warriors,Season 3,2,2,0,0,2,0,0,0,0,0,0,0
3,Bengal Warriors,Season 4,1,2,0,1,1,1,2,2,0,0,0,0
4,Bengal Warriors,Season 5,1,2,0,0,1,1,0,1,1,1,1,1
5,Bengal Warriors,Season 6,1,2,0,0,0,3,0,0,1,1,1,0
6,Bengal Warriors,Season 7,0,0,0,1,0,1,1,1,1,1,1,0
7,Bengaluru Bulls,Season 1,1,2,0,1,1,1,0,0,0,0,0,0
8,Bengaluru Bulls,Season 2,3,1,0,2,0,0,0,0,0,0,0,0
9,Bengaluru Bulls,Season 3,2,2,2,1,2,1,2,0,0,0,0,0
10,Bengaluru Bulls,Season 4,1,2,0,1,1,2,1,0,0,0,0,0
11,Bengaluru Bulls,Season 5,1,2,2,1,0,1,2,0,1,1,1,1
12,Bengaluru Bulls,Season 6,1,1,3,0,1,1,0,0,0,0,0,0
13,Bengaluru Bulls,Season 7,0,0,1,0,2,1,0,0,2,1,1,0
14,Dabang Delhi K.C.,Season 1,1,1,1,2,0,0,2,1,0,0,0,0
15,Dabang Delhi K.C.,Season 2,2,1,1,1,1,0,2,2,0,0,0,0
16,Dabang Delhi K.C.,Season 3,2,2,2,2,2,0,2,1,0,0,0,0
17,Dabang Delhi K.C.,Season 4,2,1,1,2,1,0,2,0,0,0,0,0
18,Dabang Delhi K.C.,Season 5,2,1,0,1,3,0,1,1,3,1,3,0
19,Dabang Delhi K.C.,Season 6,3,1,0,0,1,0,0,0,2,2,2,0
20,Dabang Delhi K.C.,Season 7,0,0,0,0,0,0,0,0,1,0,1,0
21,Gujarat Fortunegiants,Season 5,0,1,1,1,0,0,0,0,0,1,3,1
22,Gujarat Fortunegiants,Season 6,1,0,0,0,0,1,0,3,0,0,1,0
23,Gujarat Fortunegiants,Season 7,2,0,1,1,2,1,1,0,0,1,1,1
24,Haryana Steelers,Season 5,2,2,0,1,2,0,1,0,0,0,0,1
25,Haryana Steelers,Season 6,2,0,0,3,3,1,1,1,2,1,0,1
26,Haryana Steelers,Season 7,0,0,1,2,0,1,1,0,0,0,0,1
27,Jaipur Pink Panthers,Season 1,2,1,0,0,0,0,0,1,0,0,0,0
28,Jaipur Pink Panthers,Season 2,1,2,2,0,0,1,1,0,0,0,0,0
29,Jaipur Pink Panthers,Season 3,1,2,2,0,1,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,Patna Pirates,Season 5,1,0,2,0,1,0,0,1,2,2,0,1
39,Patna Pirates,Season 6,1,0,1,0,0,0,3,2,2,1,1,1
40,Patna Pirates,Season 7,1,0,1,1,1,1,0,2,1,1,2,0
41,Puneri Paltan,Season 1,2,2,1,2,0,2,2,1,0,0,0,0
42,Puneri Paltan,Season 2,2,2,1,2,0,1,1,2,0,0,0,0
43,Puneri Paltan,Season 3,2,1,1,1,0,0,1,0,0,0,0,0
44,Puneri Paltan,Season 4,1,2,1,1,0,1,1,1,0,0,0,0
45,Puneri Paltan,Season 5,0,1,1,1,0,0,0,1,3,0,1,0
46,Puneri Paltan,Season 6,2,1,1,1,0,2,1,0,3,1,0,1
47,Puneri Paltan,Season 7,2,1,2,1,0,1,0,0,0,1,2,1
48,Tamil Thalaivas,Season 5,1,2,2,1,1,1,2,2,0,1,0,0
49,Tamil Thalaivas,Season 6,1,2,3,1,0,1,1,3,1,1,1,0
50,Tamil Thalaivas,Season 7,1,2,1,1,1,2,1,2,0,1,1,0
51,Telugu Titans,Season 1,0,1,2,2,0,0,0,2,0,0,0,0
52,Telugu Titans,Season 2,1,0,0,1,1,0,0,2,0,0,0,0
53,Telugu Titans,Season 3,2,1,2,1,1,0,0,0,0,0,0,0
54,Telugu Titans,Season 4,0,1,0,1,2,0,0,1,0,0,0,0
55,Telugu Titans,Season 5,0,3,3,0,1,0,0,1,1,3,1,0
56,Telugu Titans,Season 6,1,0,3,0,1,1,0,3,1,1,0,2
57,Telugu Titans,Season 7,2,2,0,0,1,2,0,2,0,1,0,1
58,U Mumba,Season 1,0,0,0,1,0,1,2,1,0,0,0,0
59,U Mumba,Season 2,0,0,0,1,0,0,1,0,0,0,0,0
60,U Mumba,Season 3,0,2,0,1,0,0,0,0,0,0,0,0
61,U Mumba,Season 4,0,2,1,0,1,0,2,1,0,0,0,0
62,U Mumba,Season 5,0,0,0,2,3,1,1,0,3,0,1,1
63,U Mumba,Season 6,0,0,0,0,1,0,0,0,2,2,1,0
64,U Mumba,Season 7,0,0,2,1,0,1,0,1,0,1,1,0
65,U.P. Yoddha,Season 5,1,1,2,1,2,0,0,2,0,0,1,2
66,U.P. Yoddha,Season 6,1,2,2,1,0,0,2,3,2,0,0,2
67,U.P. Yoddha,Season 7,1,1,1,0,0,1,0,0,1,0,1,1

In [25]:
final_df=f1.drop(['match_date','time','scores','team1_score','team2_score','Winning_Team_Name','venue'],axis='columns')

# Team Stats
Incorporating the previous season wins, losses and rank of team1 and team2 as features

In [27]:
lis=[]
for i in range(0,len(files)):
    if 'standings' in files[i]:
        lis.append(files[i])
lis

['season 1_standings.csv',
 'season 2_standings.csv',
 'season 3_standings.csv',
 'season 4_standings.csv',
 'season 5_standings.csv',
 'season 6_standings.csv',
 'season 7_standings.csv']

In [28]:
f2=pd.DataFrame()
for f in lis:
    s=pd.read_csv(path+"\\"+f)
    s['Season']=f[0:8]
    f2=pd.concat([f2,s])
f2.head()

  Rank                  Team Played Won Lost Drawn Score_diff Points    Season
0    1  Jaipur Pink Panthers     14  10    3     1          0     54  season 1
1    2               U Mumba     14   8    3     3          0     51  season 1
2    3       Bengaluru Bulls     14   8    5     1          0     47  season 1
3    4         Patna Pirates     14   7    5     2          0     45  season 1
4    5         Telugu Titans     14   6    5     3          0     42  season 1

In [29]:
#Cleaning/Structuring the data
f2=f2[f2.Team!="teamteam"]
f2.Season=f2.Season.str.title()
f2['Rank']=f2.Rank.replace({'1q':1,'2q':2,'3q':3})

In [30]:
final_df['Team1_previous_seasons_wins']=0
final_df['Team1_previous_seasons_losses']=0
final_df['Team1_previous_seasons_Rank']=0
#final_df['Team1_previous_seasons_Points']=0

m=list(final_df.Team2.value_counts().index)
season_i=['Season 2','Season 3','Season 4','Season 5','Season 6','Season 7']
season_j=['Season 1','Season 2','Season 3','Season 4','Season 5','Season 6']

f2.Won=f2.Won.astype('int64')
f2.Lost=f2.Lost.astype('int64')
f2.Rank=f2.Rank.astype('int64')
f2.Points=f2.Points.astype('int64')

#For Team1
for team in m:
    for season in range(0,len(season_i)):
        i=((final_df['Team1']==team) & (final_df['Season']==season_i[season]))
        j=((f2['Team']==team) & (f2['Season']==season_j[season]))
        
        #Correctly adding wins and losses of the previous season to the df
        if f2[j]['Won'].empty: #In some cases where the team is newly formed the result is an empty series
            final_df['Team1_previous_seasons_wins'][i]=0
        elif f2[j]['Lost'].empty:
            final_df['Team1_previous_seasons_losses'][i]=0
        elif f2[j]['Rank'].empty:
            final_df['Team1_previous_seasons_Rank'][i]=0
        #elif f2[j]['Points'].empty:
            #final_df['Team1_previous_seasons_Points'][i]=0    
        else:    
            final_df['Team1_previous_seasons_wins'][i]=f2[j]['Won'].values
            final_df['Team1_previous_seasons_losses'][i]=f2[j]['Lost'].values
            final_df['Team1_previous_seasons_Rank'][i]=f2[j]['Rank'].values
            #final_df['Team1_previous_seasons_Points'][i]=f2[j]['Points'].values

C:\anaconda\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [31]:
final_df['Team2_previous_seasons_wins']=0
final_df['Team2_previous_seasons_losses']=0
final_df['Team2_previous_seasons_Rank']=0
#final_df['Team2_previous_seasons_Points']=0

m=list(final_df.Team2.value_counts().index)
season_i=['Season 2','Season 3','Season 4','Season 5','Season 6','Season 7']
season_j=['Season 1','Season 2','Season 3','Season 4','Season 5','Season 6']

for team in m:
    for season in range(0,len(season_i)):
        i=((final_df['Team2']==team) & (final_df['Season']==season_i[season]))
        j=((f2['Team']==team) & (f2['Season']==season_j[season]))
        
        #Correctly adding wins and losses of the previous season to the df
        if f2[j]['Won'].empty: #In some cases where the team is newly formed the result is an empty series
            final_df['Team2_previous_seasons_wins'][i]=0
        elif f2[j]['Lost'].empty:
            final_df['Team2_previous_seasons_losses'][i]=0
        elif f2[j]['Rank'].empty:
            final_df['Team2_previous_seasons_Rank'][i]=0    
        #elif f2[j]['Points'].empty:
            #final_df['Team2_previous_seasons_Points'][i]=0    
        else:    
            final_df['Team2_previous_seasons_wins'][i]=f2[j]['Won'].values
            final_df['Team2_previous_seasons_losses'][i]=f2[j]['Lost'].values
            final_df['Team2_previous_seasons_Rank'][i]=f2[j]['Rank'].values
            #final_df['Team2_previous_seasons_Points'][i]=f2[j]['Points'].values

C:\anaconda\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [32]:
f1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 14 columns):
match_date           652 non-null object
time                 652 non-null object
match_status         652 non-null object
Team1                652 non-null object
Team2                652 non-null object
scores               652 non-null object
venue                652 non-null object
team1_score          620 non-null float64
team2_score          620 non-null float64
Season               652 non-null object
Winning Team         652 non-null int32
Winning_Team_Name    652 non-null object
Team1_venue          652 non-null object
match_number         652 non-null int64
dtypes: float64(2), int32(1), int64(1), object(10)
memory usage: 68.8+ KB

In [33]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 13 columns):
match_status                     652 non-null object
Team1                            652 non-null object
Team2                            652 non-null object
Season                           652 non-null object
Winning Team                     652 non-null int32
Team1_venue                      652 non-null object
match_number                     652 non-null int64
Team1_previous_seasons_wins      652 non-null int64
Team1_previous_seasons_losses    652 non-null int64
Team1_previous_seasons_Rank      652 non-null int64
Team2_previous_seasons_wins      652 non-null int64
Team2_previous_seasons_losses    652 non-null int64
Team2_previous_seasons_Rank      652 non-null int64
dtypes: int32(1), int64(7), object(5)
memory usage: 63.8+ KB

In [34]:
final_df['match_status']

0           Match 1 - Completed
1      Semi-Final 1 - Completed
2           Match 2 - Completed
3      Semi-Final 2 - Completed
4           Match 3 - Completed
5           Match 4 - Completed
6           Match 5 - Completed
7           Match 6 - Completed
8           Match 7 - Completed
9           Match 8 - Completed
10          Match 9 - Completed
11         Match 10 - Completed
12         Match 11 - Completed
13         Match 12 - Completed
14         Match 13 - Completed
15         Match 14 - Completed
16         Match 15 - Completed
17         Match 16 - Completed
18         Match 17 - Completed
19         Match 18 - Completed
20         Match 19 - Completed
21         Match 20 - Completed
22         Match 21 - Completed
23         Match 22 - Completed
24         Match 23 - Completed
25         Match 24 - Completed
26         Match 25 - Completed
27         Match 26 - Completed
28         Match 27 - Completed
29         Match 28 - Completed
                 ...
622       Match 104 - Completed
623            Match 105 - Live
624        Match 106 - Upcoming
625        Match 107 - Upcoming
626        Match 108 - Upcoming
627        Match 109 - Upcoming
628        Match 110 - Upcoming
629        Match 111 - Upcoming
630        Match 112 - Upcoming
631        Match 113 - Upcoming
632        Match 114 - Upcoming
633        Match 115 - Upcoming
634        Match 116 - Upcoming
635        Match 117 - Upcoming
636        Match 118 - Upcoming
637        Match 119 - Upcoming
638        Match 120 - Upcoming
639        Match 121 - Upcoming
640        Match 122 - Upcoming
641        Match 123 - Upcoming
642        Match 124 - Upcoming
643        Match 125 - Upcoming
644        Match 126 - Upcoming
645        Match 127 - Upcoming
646        Match 128 - Upcoming
647        Match 129 - Upcoming
648        Match 130 - Upcoming
649        Match 131 - Upcoming
650        Match 132 - Upcoming
651            Final - Upcoming
Name: match_status, Length: 652, dtype: object

In [35]:
# Train and Test sets
final_df_train=final_df[final_df['match_status'].str.split('-',expand=True)[1].str.strip()=="Completed"]
final_df_test=final_df[final_df['match_status'].str.split('-',expand=True)[1].str.strip()=="Upcoming"]

In [36]:
#Separating the finals and the semifinals
eliminators=final_df_test[(final_df_test['match_status'].str.split(' ',expand=True)[0]=="Eliminator") | 
 (final_df_test['match_status'].str.split(' ',expand=True)[0]=="Final")]

In [37]:
#Getting the indices of the eliminator matches
ind=final_df_test.index[[0,1,-1]]
final_df_test=final_df_test.drop(ind)
upcoming_matches=final_df_test.copy()

In [38]:
final_df_train.head()

,match_status,Team1,Team2,Season,Winning Team,Team1_venue,match_number,Team1_previous_seasons_wins,Team1_previous_seasons_losses,Team1_previous_seasons_Rank,Team2_previous_seasons_wins,Team2_previous_seasons_losses,Team2_previous_seasons_Rank
0,Match 1 - Completed,U Mumba,Jaipur Pink Panthers,Season 1,1,Away,1,0,0,0,0,0,0
2,Match 2 - Completed,Dabang Delhi K.C.,Bengaluru Bulls,Season 1,0,Away,2,0,0,0,0,0,0
4,Match 3 - Completed,Bengaluru Bulls,Puneri Paltan,Season 1,1,Away,3,0,0,0,0,0,0
5,Match 4 - Completed,U Mumba,Bengal Warriors,Season 1,1,Away,4,0,0,0,0,0,0
6,Match 5 - Completed,Puneri Paltan,Dabang Delhi K.C.,Season 1,0,Away,5,0,0,0,0,0,0

In [39]:
final_df_test.head()

,match_status,Team1,Team2,Season,Winning Team,Team1_venue,match_number,Team1_previous_seasons_wins,Team1_previous_seasons_losses,Team1_previous_seasons_Rank,Team2_previous_seasons_wins,Team2_previous_seasons_losses,Team2_previous_seasons_Rank
624,Match 106 - Upcoming,Telugu Titans,Bengal Warriors,Season 7,0,Away,106,8,13,5,12,8,2
625,Match 107 - Upcoming,Jaipur Pink Panthers,Puneri Paltan,Season 7,0,Home,107,6,13,5,8,12,4
626,Match 108 - Upcoming,Patna Pirates,Dabang Delhi K.C.,Season 7,0,Away,108,9,11,4,11,9,3
627,Match 109 - Upcoming,U Mumba,Bengaluru Bulls,Season 7,0,Away,109,15,5,2,13,7,1
628,Match 110 - Upcoming,Jaipur Pink Panthers,Telugu Titans,Season 7,0,Home,110,6,13,5,8,13,5

In [40]:
final_df_train=final_df_train.drop(['Team1','Team2','match_number','match_status'],axis='columns')
final_df_test=final_df_test.drop(['Team1','Team2','match_number','match_status'],axis='columns')

# Preprocessing and modeling

In [41]:
predictors=final_df_train.drop('Winning Team',axis='columns')
predictors=pd.get_dummies(predictors,drop_first=True)
target=final_df_train['Winning Team']

In [42]:
pd.get_dummies(final_df_train,drop_first=True).corr()

,Winning Team,Team1_previous_seasons_wins,Team1_previous_seasons_losses,Team1_previous_seasons_Rank,Team2_previous_seasons_wins,Team2_previous_seasons_losses,Team2_previous_seasons_Rank,Season_Season 2,Season_Season 3,Season_Season 4,Season_Season 5,Season_Season 6,Season_Season 7,Team1_venue_Home
Winning Team,1.000000,0.070724,-0.089212,-0.121603,-0.029554,0.052241,0.070811,0.025569,0.025569,0.003090,-0.061330,0.037755,-0.036183,-0.136796
Team1_previous_seasons_wins,0.070724,1.000000,0.183578,-0.089849,0.422057,0.511083,0.279519,-0.034015,-0.014881,-0.013606,-0.285205,0.367593,0.345917,-0.059385
Team1_previous_seasons_losses,-0.089212,0.183578,1.000000,0.795418,0.490107,0.395199,0.160695,-0.035953,-0.014466,-0.016994,-0.263651,0.382329,0.300725,0.043314
Team1_previous_seasons_Rank,-0.121603,-0.089849,0.795418,1.000000,0.233574,0.132301,0.154647,0.147875,0.150190,0.150190,-0.035038,0.037516,-0.001959,0.112260
Team2_previous_seasons_wins,-0.029554,0.422057,0.490107,0.233574,1.000000,0.181548,-0.061061,-0.019501,-0.008049,-0.005504,-0.295992,0.376819,0.311447,-0.012485
Team2_previous_seasons_losses,0.052241,0.511083,0.395199,0.132301,0.181548,1.000000,0.818174,-0.027238,-0.001331,-0.007499,-0.307361,0.350173,0.347252,-0.032625
Team2_previous_seasons_Rank,0.070811,0.279519,0.160695,0.154647,-0.061061,0.818174,1.000000,0.154697,0.163801,0.156973,-0.116139,0.030454,0.065080,0.000012
Season_Season 2,0.025569,-0.034015,-0.035953,0.147875,-0.019501,-0.027238,0.154697,1.000000,-0.104882,-0.104882,-0.174110,-0.174928,-0.146678,0.096048
Season_Season 3,0.025569,-0.014881,-0.014466,0.150190,-0.008049,-0.001331,0.163801,-0.104882,1.000000,-0.104882,-0.174110,-0.174928,-0.146678,0.048968
Season_Season 4,0.003090,-0.013606,-0.016994,0.150190,-0.005504,-0.007499,0.156973,-0.104882,-0.104882,1.000000,-0.174110,-0.174928,-0.146678,0.060738
Season_Season 5,-0.061330,-0.285205,-0.263651,-0.035038,-0.295992,-0.307361,-0.116139,-0.174110,-0.174110,-0.174110,1.000000,-0.290389,-0.243491,-0.098126
Season_Season 6,0.037755,0.367593,0.382329,0.037516,0.376819,0.350173,0.030454,-0.174928,-0.174928,-0.174928,-0.290389,1.000000,-0.244637,-0.100695
Season_Season 7,-0.036183,0.345917,0.300725,-0.001959,0.311447,0.347252,0.065080,-0.146678,-0.146678,-0.146678,-0.243491,-0.244637,1.000000,0.022266
Team1_venue_Home,-0.136796,-0.059385,0.043314,0.112260,-0.012485,-0.032625,0.000012,0.096048,0.048968,0.060738,-0.098126,-0.100695,0.022266,1.000000

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(predictors,target,train_size=0.7,random_state=100)

C:\anaconda\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [44]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
clf3 = LogisticRegression(random_state=57)
clf3.fit(x_train, y_train)
clf1=RandomForestClassifier(n_estimators=1400,max_depth=20,random_state=57)
clf2=AdaBoostClassifier(n_estimators=1000,learning_rate=1,random_state=57)
clf4=XGBClassifier(random_state=57)
clf4.fit(x_train,y_train)
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

C:\anaconda\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
predictions1=clf1.predict(x_test)
predictions2=clf2.predict(x_test)
predictions3=clf3.predict(x_test)
predictions4=clf4.predict(x_test)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from sklearn.metrics import accuracy_score
print("RF ",accuracy_score(y_test,predictions1))
print("Ada ",accuracy_score(y_test,predictions2))
print("Logreg ",accuracy_score(y_test,predictions3))
print("XGBoost ",accuracy_score(y_test,predictions4))

In [ ]:
clf1.feature_importances_

In [ ]:
predictions3

# Predicting on unseen data

In [ ]:
predictors_test=final_df_test.drop('Winning Team',axis='columns')
predictors_test=pd.get_dummies(predictors_test,drop_first=True)

In [ ]:
lis=[]
for i in range(0,len(list(predictors.columns))):
    if 'Season' in list(predictors.columns)[i]:
        lis.append(list(predictors.columns)[i])
lis

In [ ]:
for i in lis:
    predictors_test[i]=0
predictors_test['Season_Season 7']=1

In [ ]:
final_predictions=clf3.predict(predictors_test)

In [ ]:
final_df_test.shape

In [ ]:
final_predictions

In [ ]:
predictions_df=upcoming_matches[['Team1','Team2','match_status']]

In [ ]:
predictions_df['Predicted_Winner']=final_predictions

In [ ]:
predictions_df['Winning_Team_Name']=np.where(predictions_df['Predicted_Winner']==0,predictions_df['Team2'],predictions_df['Team1'])
predictions_df['Losing_Team_Name']=np.where(predictions_df['Predicted_Winner']==0,predictions_df['Team1'],predictions_df['Team2'])

In [ ]:
predictions_df

In [ ]:
#Storing the predicted number of wins and losses per team
w=predictions_df.groupby('Winning_Team_Name')['Winning_Team_Name'].count()
l=predictions_df.groupby('Losing_Team_Name')['Losing_Team_Name'].count()

In [ ]:
team_names

In [ ]:
season_7_standings=f2[f2['Season']=='Season 7']

In [ ]:
season_7_standings

# Getting the new standings according to our predictions -

In [ ]:
new_wins=[]
new_losses=[]
for team in season_7_standings.Team:
    if team in w.index:
        new_wins.append(int(season_7_standings[season_7_standings.Team==team]['Won'])+int(w[team]))
    else:
        new_wins.append(int(season_7_standings[season_7_standings.Team==team]['Won']))
    if team in l.index:
        new_losses.append(int(season_7_standings[season_7_standings.Team==team]['Lost'])+int(l[team]))
    else:
        new_losses.append(int(season_7_standings[season_7_standings.Team==team]['Lost']))

In [ ]:
new_losses

In [ ]:
season_7_standings_new=season_7_standings.copy()
season_7_standings_new['Won']=new_wins
season_7_standings_new['Lost']=new_losses

In [ ]:
season_7_standings_new['Points']=(season_7_standings_new['Won']*5)+(season_7_standings_new['Drawn']*3)

In [ ]:
season_7_standings_new.drop(['Played','Score_diff'],axis=1).sort_values('Points',ascending=False)

# Predicting the winner
The tournament will run as following - 
- Eliminator matches which will decide the teams which battle for the Semifinals
- Semifinals 1 and 2
- Finals

In [ ]:
final_df_test.head()

In [ ]:
predictors

In [ ]:
finals=eliminators.iloc[-1]
sf_eliminators=eliminators.iloc[0:2]

In [ ]:
sf_eliminators

# Eliminator matches

In [ ]:
#A simple function to predict the winners of the elimination matches
def predict_winners(team1,team2,team1_w,team1_l,team1_r,team2_w,team2_l,team2_r,predictors,l):
    predictors['Team1']=team1
    predictors['Team2']=team2
    predictors['Team1_previous_seasons_wins']=team1_w
    predictors['Team1_previous_seasons_losses']=team1_l
    predictors['Team1_previous_seasons_Rank']=team1_r
    predictors['Team2_previous_seasons_wins']=team2_w
    predictors['Team2_previous_seasons_losses']=team2_l
    predictors['Team2_previous_seasons_Rank']=team2_r

    predictors_sf=predictors.drop(['Winning Team','match_status','Team1','Team2','match_number','Team1_venue'],axis='columns')
    predictors_sf=pd.get_dummies(predictors_sf)
    #We know that no team plays at home in the eliminator matches so there will be no home team venue
    predictors_sf['Team1_venue_Home']=0
    lis=[]
    for i in range(0,len(l)):
        if 'Season' in l[i]:
            lis.append(l[i])
    #lis
    for i in lis:
        predictors_sf[i]=0
    predictors_sf['Season_Season 7']=1    
    final_predictions_sf=clf3.predict(predictors_sf)
    return(final_predictions_sf)

In [ ]:
#The teams which qualified for the semifinal matches (as determined by the predicted standings)
team1=['Bengaluru Bulls','U.P. Yoddha']
team2=['Haryana Steelers','U Mumba']
team1_w=[13,8]
team1_l=[7,10]
team1_r=[1,3]
team2_w=[6,15]
team2_l=[14,5]
team2_r=[6,2]
predictors=sf_eliminators
l=list(predictors_test.columns)

In [ ]:
winners=predict_winners(team1,team2,team1_w,team1_l,team1_r,team2_w,team2_l,team2_r,predictors,l)
winners

# Elimination matches winners - 
In both mathces Team1 wins (as denoted by the predictions [1,1]).

So, the winners are - 

'Bengaluru Bulls' and  'U.P. Yoddha'

# Predicting the semifinals -

In [ ]:
#We can modify sf_eliminators to obtain the two sf matches
semifinals=sf_eliminators.copy()

In [ ]:
#The teams which qualified for the semifinal matches (as determined by the predicted standings)
team1=['Dabang Delhi K.C.','Bengal Warriors']
team2=['Bengaluru Bulls','U.P. Yoddha']
team1_w=[11,12]
team1_l=[9,8]
team1_r=[3,2]
team2_w=[13,8]
team2_l=[7,10]
team2_r=[1,3]
predictors=semifinals
l=list(predictors_test.columns)

In [ ]:
sf_winners=predict_winners(team1,team2,team1_w,team1_l,team1_r,team2_w,team2_l,team2_r,predictors,l)
sf_winners

# Semifinal Winners

As predicted above the semifinal winners are - 
'Bengaluru Bulls' and 'Bengal Warriors'

# Predicting the finals

In [ ]:
finals=pd.DataFrame(finals).transpose()
finals

In [ ]:
#To predict the finals 
team1=['Bengaluru Bulls']
team2=['Bengal Warriors']
team1_w=[13]
team1_l=[7]
team1_r=[1]
team2_w=[12]
team2_l=[8]
team2_r=[2]
predictors=finals
l=list(predictors_test.columns)

In [ ]:
final_winner=predict_winners(team1,team2,team1_w,team1_l,team1_r,team2_w,team2_l,team2_r,predictors,l)
final_winner

# The winner of the finals is - 

## Bengaluru Bulls